version: '3.8'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
